name: Build JAR
on: [ workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Build Jar
        run: ./gradlew build
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: BaublesEX More Slots JAR
          path: build/libs/BaublesEX-More-Slots-*.jar
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: BaublesEX-More-Slots-*
          path: ./downloads

