name: Build JAR
on: [ workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Your build step, replace with your specific build command for the mod
      - name: Build mod
        run: ./gradlew build

      # Capture the .jar file name dynamically (adjust the path if necessary)
      - name: Find the versioned .jar file
        id: jar-name
        run: |
          JAR_NAME=$(ls build/libs/*.jar | grep -E '.*\.jar')
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

      # Optionally rename the .jar to something generic (without the version number)
      - name: Rename the .jar file (optional)
        run: |
          mv $JAR_NAME build/libs/BaublesEx-More-Slots.jar
        if: success()  # Only rename if the jar was found

      # Upload the .jar file
      - name: Upload .jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: $JAR_NAME
          path: ${{ env.JAR_NAME }}  # Or ${{ env.JAR_NAME }} if you want to keep the original name
      - uses: Shopify/upload-to-release@v2.0.0
        with:
          name: my-artifact
          path: build/lib/${{ env.JAR_NAME }}
          repo-token: ${{ secrets.AUTO_RELEASE }}
