name: Build JAR
on: [workflow_dispatch, push]
permissions:
  contents: write
  pull-requests: write
  releases: write  # Required to create releases and upload assets
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the mod
      - name: Build mod
        run: ./gradlew build

      # Capture the version number from build.gradle
      - name: Get version from build.gradle
        id: get_version
        run: |
          VERSION=$(grep 'version =' build.gradle | sed -E 's/.*= *["'\'']?([^"'\'']+)["'\'']?.*/\1/' | tr -d ' ')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Find the JAR file dynamically
      - name: Find the versioned .jar file
        id: find_jar
        run: |
          JAR_NAME=$(ls build/libs/BaublesEX-More-Slots-*.jar)
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

      # Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the .jar file as a release asset
      - name: Upload .jar artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.JAR_NAME }}
          asset_name: BaublesEX-More-Slots-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure it's being passed here too
