name: Build JAR
on: [workflow_dispatch, push]
permissions:
  contents: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Your build step, replace with your specific build command for the mod
      - name: Build mod
        run: ./gradlew build

      # Capture the .jar file name dynamically (adjust the path if necessary)
      - name: Find the versioned .jar file
        id: find_jar
        run: |
          JAR_NAME=$(ls build/libs/BaublesEX-More-Slots-*.jar)
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

      # Upload the .jar file
      - name: Upload .jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: BaublesEX-More-Slots
          path: ${{ env.JAR_NAME }}
          
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.AUTO_RELEASE }}
          release-type: simple
