name: Build JAR
on: [workflow_dispatch, push]
permissions:
  contents: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the mod
      - name: Build mod
        run: ./gradlew build

      # Capture the version number from build.gradle
      - name: Get version from build.gradle
        id: get_version
        run: |
          VERSION=$(grep 'version =' build.gradle | sed 's/.*= \(.*\)/\1/' | tr -d ' ')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Find the JAR file dynamically
      - name: Find the versioned .jar file
        id: find_jar
        run: |
          JAR_NAME=$(ls build/libs/BaublesEX-More-Slots-*.jar)
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

      # Upload the .jar file with version in the name
      - name: Upload .jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: BaublesEX-More-Slots-${{ env.VERSION }}
          path: ${{ env.JAR_NAME }}
          
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.AUTO_RELEASE }}
          release-type: simple
